<a href="https://colab.research.google.com/github/udaykiranreddykondreddy/Code-for-learn-machinelearning/blob/master/performance_metric/Confusion_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="http://drive.google.com/uc?export=view&id=1xZggtEjnrMp9QBm_4q5RJIfJyfSoSJ9p" height="150" align="left"/>
<h1>&nbsp;<a href="https://instagram.com/learn.machinelearning">Learn.MachineLearning</a></h1>
<h2>&nbsp;Confusion Matrix, Precisioin, Recall and F1 score</h2>


<img src="http://drive.google.com/uc?export=view&id=1Mt2aVaXZF0k3nzzix5h1iwL1womr8oaB" height="250"/>

**<h3> Load dataset </h3>**

In [0]:
# Import libraries 
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
import numpy as np

In [0]:
# Load data(We will be using breast cancer dataset)
data = datasets.load_breast_cancer()

In [0]:
x_data, y_data = data["data"], data["target"]

In [67]:
np.unique(y_data)

array([0, 1])

In [0]:
# split data into train and test
X_train, X_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.30, random_state=35)

In [69]:
# Train a model with logistic regression
clf = LogisticRegression().fit(X_train, y_train)
predicted_values = clf.predict(X_test)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [0]:
results = confusion_matrix(y_test, predicted_values,labels=[0,1])

In [71]:
print(results)

[[ 52   7]
 [  5 107]]


**So lets say 0 as positive and 1 as negative**

- True Positives (tp): Actual value is 0 and predicted value is 0
- Flase Positives (fp): Actual value is 1 and predicted value is 0
- True Negatives (tn): Actual value is 1 and predicted value is 1
- False Negatives (fn): Actual value is 0 and predicted value is 1

In [72]:
tp = results[0][0]
fp = results[1][0]
tn = results[1][1]
fn = results[0][1]
print("Total predicted Positives ", tp + fp)
print("Total predicted Negatives ", tn + fn)
print("True Positives ", tp)
print("False Positives ", fp)
print("True Negatives ", tn)
print("False Negatives ", fn)

Total predicted Positives  57
Total predicted Negatives  114
True Positives  52
False Positives  5
True Negatives  107
False Negatives  7


**<h3> Precision </h3>**

- It is the ratio of tp to tp + fp
```
Precision = tp/(tp+fp)
```
- It says how many positive values it predicted correctly from the total perdicted positive values

In [73]:
precision = tp / (tp+fp)
print(precision)

0.9122807017543859


**<h3> Recall </h3>**

- It is also called as sensitivity or True Positive Rate 
- It is the ratio of tp to tp + fn
```
Recall = tp/(tp+fn)
```
- It says how many positive values it predicted correctly from the total actual positive values

In [74]:
recall = tp / (tp+fn)
print(recall)

0.8813559322033898


**<h3> Trade-off </h3>**
- High Recall and low Precision
- Low Recall and High Precision

**<h3> Errors </h3>**

- 2 types of errors Type I and Type II
- False Positives are Type I error
- False Positive Rate (caused by Type I Error)
```
False Positive Rate = fp / (fp+tn)
```
- Flase negatives are Type II error
- False negative Rate (caused by Type II Error)
```
False Negatve Rate = fn / (fn+tp)
```

In [75]:
fpr = fp / (fp+tn)
print("False Positive Rate ", fpr)
fnr = fn / (fn+tp)
print("False Negative Rate ", fnr)

False Positive Rate  0.044642857142857144
False Negative Rate  0.11864406779661017


**<h3> F1 Score </h3>**

- It is a Harmonic Mean of both Precision and Recall
```
f_score = 2*recall*precision / (recall + precision)
```

In [76]:
f_score_svm = 2*recall*precision / (recall + precision)
print("Precision value ",precision)
print("Recall value ",recall)
print("F Score ",f_score_svm)

Precision value  0.9122807017543859
Recall value  0.8813559322033898
F Score  0.8965517241379309


In [77]:
# Train a model with SVM
#?svm.SVC()
clf = svm.SVC().fit(X_train, y_train)
predicted_values = clf.predict(X_test)
results = confusion_matrix(y_test, predicted_values,labels=[0,1])
print(results)
tp1 = results[0][0]
fp1 = results[1][0]
tn1 = results[1][1]
fn1 = results[0][1]
precision_logistic = tp1 / (tp1+fp1)
recall_logistic = tp1 / (tp1+fn1)
f_score_logistic = 2*recall_logistic*precision_logistic / (recall_logistic + precision_logistic)
print("Precision value ",precision_logistic)
print("Recall value ",recall_logistic)
print("F Score ",f_score_logistic)


[[ 48  11]
 [  1 111]]
Precision value  0.9795918367346939
Recall value  0.8135593220338984
F Score  0.888888888888889
